name: esc_utils
description: 小票打印机 *ESC* 数据转换工具，主要用于将 image 图像转换成小票打印机可识别的字节数组
version: 0.0.1
homepage: https://github.com/liyufengrex/esc_utils

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.3"

dependencies:
  flutter:
    sdk: flutter
  hex: ^0.2.0
  gbk_codec: ^0.4.0
  image: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
